stages:
  - build

job_test:
  stage: build
  tags:
    - pc-toki
  script:
    - echo "Début du build sur mon PC Linux Mint..."
    - mvn --version
    - mvn clean compile
    - echo "Fin du build sur mon PC Linux Mint..."
