stages:
  - build

job_test:
  stage: build
  tags:
    - pc-toki  # Remplace par le tag exact que tu as mis sur GitLab
  script:
    - echo "Début du build sur mon PC..."
    - mvn --version
    - mvn clean compile