services:
  app:
    build: .
    container_name: wildfly-app
    ports:
      - "8080:8080"
      - "9990:9990"
    environment:
      # C'est ici que tu injectes les variables lues par le Dockerfile
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=questionnaire
      - DB_USER=toki
      - DB_PASS=toki
    volumes:
      - .:/app
    # On retire le "command" complexe car tout est déjà prêt dans l'image
    depends_on:
      - db
    networks:
      - jakarta-network

  db:
    image: postgres:16
    container_name: postgres-db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: questionnaire
      POSTGRES_USER: toki
      POSTGRES_PASSWORD: toki
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - jakarta-network

volumes:
  postgres_data:

networks:
  jakarta-network:
    driver: bridge