
services:
  app:
    build: .
    container_name: wildfly-app
    ports:
      - "8080:8080"
      - "9990:9990"
    volumes:
      - ./configure-wildfly.cli:/tmp/configure-wildfly.cli
      - ./entrypoint.sh:/opt/jboss/entrypoint.sh
    command: >
      /bin/bash -c "
        /opt/jboss/wildfly/bin/standalone.sh -b 0.0.0.0 -bmanagement 0.0.0.0 &
        echo 'Attente du démarrage de WildFly...';
        sleep 20;
        echo 'Exécution du script de configuration CLI...';
        /opt/jboss/wildfly/bin/jboss-cli.sh --connect --file=/tmp/configure-wildfly.cli;
        tail -f /opt/jboss/wildfly/standalone/log/server.log"
    depends_on:
      - db
    networks:
      - jakarta-network

  db:
    image: postgres:16
    container_name: postgres-db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: questionnaire
      POSTGRES_USER: toki
      POSTGRES_PASSWORD: toki
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - jakarta-network

volumes:
  postgres_data:

networks:
  jakarta-network:
    driver: bridge