version: '3.8'

services:
  app:
    build: .
    container_name: jakarta-app
    ports:
      - "8080:8080"
      - "9990:9990"
    volumes:
      - ./lib/postgresql-42.6.0.jar:/tmp/postgresql-42.6.0.jar
      - ./configure-wildfly.cli:/tmp/configure-wildfly.cli
    command: >
      /bin/bash -c "
        /opt/jboss/wildfly/bin/standalone.sh -b 0.0.0.0 -bmanagement 0.0.0.0 &
        sleep 20;
        /opt/jboss/wildfly/bin/jboss-cli.sh --connect --file=/tmp/configure-wildfly.cli;
        tail -f /opt/jboss/wildfly/standalone/log/server.log"
    depends_on:
      - db
    networks:
      - jakarta-network

  # Base de données PostgreSQL
  db:
    image: postgres:16
    container_name: jakarta-db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: questionnaire
      POSTGRES_USER: toki
      POSTGRES_PASSWORD: toki
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - jakarta-network
volumes:
  postgres_data:

networks:
  jakarta-network:
    driver: bridge